//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMReservation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMReservation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string strActionEditCom {
            get {
                return ResourceManager.GetString("strActionEditCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Release 的本地化字符串。
        /// </summary>
        internal static string strActionRelease {
            get {
                return ResourceManager.GetString("strActionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +Reserve 的本地化字符串。
        /// </summary>
        internal static string strActionReserve {
            get {
                return ResourceManager.GetString("strActionReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string strActionSaveCom {
            get {
                return ResourceManager.GetString("strActionSaveCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Kill Secure CRT 的本地化字符串。
        /// </summary>
        internal static string strActionSecureCrtKill {
            get {
                return ResourceManager.GetString("strActionSecureCrtKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +Open Secure CRT 的本地化字符串。
        /// </summary>
        internal static string strActionSecureCrtOpen {
            get {
                return ResourceManager.GetString("strActionSecureCrtOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +Wait 的本地化字符串。
        /// </summary>
        internal static string strActionWaitAdd {
            get {
                return ResourceManager.GetString("strActionWaitAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Wait 的本地化字符串。
        /// </summary>
        internal static string strActionWaitRemove {
            get {
                return ResourceManager.GetString("strActionWaitRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM Reservation 的本地化字符串。
        /// </summary>
        internal static string strAppName {
            get {
                return ResourceManager.GetString("strAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string strFilterByAll {
            get {
                return ResourceManager.GetString("strFilterByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal Reservation 的本地化字符串。
        /// </summary>
        internal static string strFilterIllegal {
            get {
                return ResourceManager.GetString("strFilterIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved by Me 的本地化字符串。
        /// </summary>
        internal static string strFilterReservedByMe {
            get {
                return ResourceManager.GetString("strFilterReservedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved by Others 的本地化字符串。
        /// </summary>
        internal static string strFilterReservedByOthers {
            get {
                return ResourceManager.GetString("strFilterReservedByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string strFilterRunning {
            get {
                return ResourceManager.GetString("strFilterRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Expired 的本地化字符串。
        /// </summary>
        internal static string strFilterTimeExpired {
            get {
                return ResourceManager.GetString("strFilterTimeExpired", resourceCulture);
            }
        }
    }
}
