//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMReservation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMReservation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string strActionEditCom {
            get {
                return ResourceManager.GetString("strActionEditCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Release.
        /// </summary>
        internal static string strActionRelease {
            get {
                return ResourceManager.GetString("strActionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Reserve.
        /// </summary>
        internal static string strActionReserve {
            get {
                return ResourceManager.GetString("strActionReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strActionSaveCom {
            get {
                return ResourceManager.GetString("strActionSaveCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Kill Secure CRT.
        /// </summary>
        internal static string strActionSecureCrtKill {
            get {
                return ResourceManager.GetString("strActionSecureCrtKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Open Secure CRT.
        /// </summary>
        internal static string strActionSecureCrtOpen {
            get {
                return ResourceManager.GetString("strActionSecureCrtOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Wait.
        /// </summary>
        internal static string strActionWaitAdd {
            get {
                return ResourceManager.GetString("strActionWaitAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Wait.
        /// </summary>
        internal static string strActionWaitRemove {
            get {
                return ResourceManager.GetString("strActionWaitRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Reservation.
        /// </summary>
        internal static string strAppName {
            get {
                return ResourceManager.GetString("strAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaiable.
        /// </summary>
        internal static string strFilterAvaiable {
            get {
                return ResourceManager.GetString("strFilterAvaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string strFilterByAll {
            get {
                return ResourceManager.GetString("strFilterByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Reservation.
        /// </summary>
        internal static string strFilterIllegal {
            get {
                return ResourceManager.GetString("strFilterIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved by Me.
        /// </summary>
        internal static string strFilterReservedByMe {
            get {
                return ResourceManager.GetString("strFilterReservedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved by Others.
        /// </summary>
        internal static string strFilterReservedByOthers {
            get {
                return ResourceManager.GetString("strFilterReservedByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string strFilterRunning {
            get {
                return ResourceManager.GetString("strFilterRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Expired.
        /// </summary>
        internal static string strFilterTimeExpired {
            get {
                return ResourceManager.GetString("strFilterTimeExpired", resourceCulture);
            }
        }
    }
}
